# Generated by Django 5.2.6 on 2025-10-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.CharField(default='alt_text', max_length=200),
        ),
    ]
