# Generated by Django 5.2.6 on 2025-10-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_media_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
    ]
