# Generated by Django 5.2.6 on 2025-10-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_media_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='associated_media',
            field=models.ForeignKey(default=4, help_text='The Image/Video to pair with the section.', on_delete=django.db.models.deletion.CASCADE, related_name='associated_media', to='gallery.media'),
        ),
    ]
