# Generated by Django 5.2.6 on 2025-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_category_associated_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='list_position',
            field=models.IntegerField(default=0),
        ),
    ]
