# Generated by Django 5.2.6 on 2025-10-17 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_category_list_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this media belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='gallery.category'),
        ),
    ]
