# Generated by Django 5.2.6 on 2025-10-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_migrate_associated_media_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='associated_media',
        ),
    ]
