# Generated by Django 5.2.6 on 2025-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Name of the about section (e.g. Bio, Exhibitions)', max_length=200)),
                ('section_information', models.TextField(max_length=3000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('media', models.ManyToManyField(blank=True, to='gallery.media')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('section_name',)},
            },
        ),
    ]
